### PR TITLE
New endpoints for Microsoft & DeepL | MyMemory language detecting fixes | Minor fixes

### LINKED ISSUE #28: Got another translator for you.
https://www.translatedict.com

its pretty good, you should add it to this also.

### PR DESCRIPTION
**Pull request by ZhymabekRoman**
Closes #28, #81, #65, #75

### CODE REVIEW

**Comment by ZhymabekRoman** [comment]
@Animenosekai, this PR also ready. I made some huge architectural changes, let me know if there is a problem or something like that.

**Comment by ZhymabekRoman** [comment]
I found caching problem, if we specify custom keyword argument like in DeepL translate function `fromality="formal"`,  and we change to `fromality="informal"`, `translatepy` responses from cache

**Comment by Animenosekai** [comment]
Before merging, could you change the name of the `base_agregator.py` file to `base_aggregator.py`

**Comment by ZhymabekRoman** [comment]
Yep, I'm sorry for this mistake

**Pull request merged**
