### PR TITLE
New translate service: Promt

### PR DESCRIPTION
**Pull request by ZhymabekRoman**
Hi. How are you, mate? I am implementing a new translation service by reverse engineering Android application. The way they have implemented language pair generation is just ... rubbish. I tried to port the implementation from Java and I think I succeeded.

### CODE REVIEW

**Comment by Animenosekai** [comment]
wow I'm so dumb I haven't merged it yet...

Is this good to go in the `next` branch ?

**Comment by ZhymabekRoman** [comment]
Hi @Animenosekai, I think yes

**Comment by Animenosekai** [comment]
Alright let me change the target branch

**Comment by Animenosekai** [comment]
yay 👍

**Pull request merged**
