### PR TITLE
add: new size based LRU cache & minor fixes

### LINKED ISSUE #58: [New] Size limited LRU cache
I made a small working prototype of the cache implementation on top of OrderedDict. Please write what can be improved.

https://gist.github.com/ZhymabekRoman/a9c7a25c155dfdea52277cc74f28fa65

### PR DESCRIPTION
**Pull request by ZhymabekRoman**
Closes #58

### CODE REVIEW

**Comment by ZhymabekRoman** [comment]
Hmmm, test freezes.

**Comment by ZhymabekRoman** [comment]
So 100 threads seems to be too much for a single-core machine. There are two solutions: use gevent, or use parallelism. I don't know what solution will be eligible for translatepy.

**Comment by Animenosekai** [comment]
> So 100 threads seems to be too much for a single-core machine. There are two solutions: use gevent, or use parallelism. I don't know what solution will be eligible for translatepy.

This is weird since Python should really allocate threads if it can

**Comment by ZhymabekRoman** [comment]
@Animenosekai, So even with a 1 thread pool, Github CI just hangs ([link](https://github.com/Scorebook-Fruit-Seizing/translate/commit/bccbe2a2bc0b616566fd4ca1a391cb9080b61c31)). Maybe we should use asyncio for lru_cache?

**Comment by Animenosekai** [comment]
> @Animenosekai, So even with a 1 thread pool, Github CI just hangs ([link](https://github.com/Scorebook-Fruit-Seizing/translate/commit/bccbe2a2bc0b616566fd4ca1a391cb9080b61c31)). Maybe we should use asyncio for lru_cache?

Do you really think it hangs because of the ThreadPool ? Seems weird that GitHub Actions have issues with such a common object

**Comment by ZhymabekRoman** [comment]
> Do you really think it hangs because of the ThreadPool ? Seems weird that GitHub Actions have issues with such a common object

I probably came to the wrong conclusion, in fact I did set the thread pool size to zero and there were no changes to the hangs.

**Comment by ZhymabekRoman** [comment]
Test hanging is fixed!

**Pull request merged**
