### PR TITLE
refactor: CLI

### PR DESCRIPTION
**Pull request by ZhymabekRoman**

### CODE REVIEW

**Comment by ZhymabekRoman** [comment]
@Animenosekai, I think this PR is done. Idk what I can edit

**Comment by Animenosekai** [comment]
> @Animenosekai, I think this PR is done. Idk what I can edit

Can I merge your PRs in the `next` branch ?

**Comment by ZhymabekRoman** [comment]
> Can I merge your PRs in the `next` branch ?

@Animenosekai, yeap

**Comment by Animenosekai** [comment]
> > Can I merge your PRs in the `next` branch ?
> 
> @Animenosekai, yeap

(btw check discord)

**Pull request merged**
